import "@/app/globals.css";
import type { Metadata } from "next";
import "../globals.css";
import { Inter, Suwannaphum } from "next/font/google";
import SideBarProfileComponent from "@/components/ProfileComponent/SideBarProfileComponent";
import NavbarPage from "@/components/Navbar/NavbarPage";
import FooterPage from "@/components/Footer/FooterPage";
const suwannaphum = Suwannaphum({
  subsets: ["khmer"],
  weight: ["400", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${suwannaphum} ${inter} antialiased `}
      >
        <NavbarPage/>
        <div className="flex bg-[#F3FBF9]  h-auto w-full lg:flex-row max-w-8xl mx-auto  m-0">
          {/* Sidebar */}
          {/* <aside className="xl:w-96 xl:m-20 lg:w-1/4 lg:m-20"> */}
            <SideBarProfileComponent />
          {/* </aside> */}

          {/* Main Content */}
          <main className="xl:w-3/4 w-full py-8 px-8 lg:w-3/4">{children}</main>
        </div>
        <FooterPage/>
      </body>
    </html>
  );
}
